const ORDER_LIST = [
    {
        id: '01',
        name: "Angebot 1 - Kindermenü",
        text: " Knusprige Chicken Nuggets, Pommes, eine Caprisonne und ein Spielzeug nach Wahl",
        filter: ['kids menü', 'kinder', 'angebote', 'halal', 'kleiner hunger'],
        price: 7.99,
    },
    {
        id: '02',
        name: "Angebot 2 - Burgerliebhaber",
        text: "2 Cheesburger - Frisches Rinderhackfleisch, Blattsalat, Gurken, Zwiebeln mit hausgemachter Burgersauce",
        filter: ['hauptgang', 'angebote', 'halal'],
        price: 18.99,
    },
    {
        id: '03',
        name: 'Angebot 3 - 3 Gang Menü',
        text: 'Eine kräftige Gemüsesuppe, Cheesburger mit Pommes und als Dessert ein Orangen Mohnpafait',
        filter: ['hauptgang', 'angebote', 'halal', 'vorspeise', 'dessert'],
        price: 22.99,
    },
    {
        id: '05',
        name: 'Salat mit Kräuterdressing',
        text: 'Frischer knackiger Blattsalat mit Tomaten, Paprika und Gruken, dazu reichen wir ein hauseigenes Kräuterdressing',
        filter: ['vorspeise', 'halal', 'vegan', 'vegetarisch', 'kleiner hunger',],
        price: 5.99,
    },
    {
        id: '06',
        name: 'Thunfischsalat mit Joghurtdressing',
        text: 'Knackiger Blattsalat mit Tomaten, Paprika, Gruken, Ei und Thunfisch, dazu reichen wir ein hauseigenes Joghurtdressing',
        filter: ['vorspeise', 'halal', 'vegetarisch', 'kleiner hunger'],
        price: 8.99,
    },
    {
        id: '10',
        name: 'Bruchetta',
        text: 'Frisches Tomatentatar auf Kräuterbagette, verfeinert mit frischen Kräutern aus dem heimischen Garten',
        filter: ['vorspeise', 'halal', 'vegan', 'vegetarisch', 'kleiner hunger'],
        price: 9.99,
    },
    {
        id: '11',
        name: 'Gemüsesuppe',
        text: 'Eine frische kräftige Gemüsesuppe mit Baguette, nach Art des Hauses',
        filter: ['vorspeise', 'kleiner hunger', 'vegetarian', 'vegan', 'halal'],
        price: 8.99,
    },
    {
        id: '50',
        name: "Cheesburger und Pommes",
        text: "Frisches Rinderhackfleisch, Blattsalat, Gurken, Zwiebeln mit hausgemachter Burgersauce und dazu Pommes",
        filter: ['hauptgang', 'halal'],
        price: 11.99,
    },
    {
        id: '51',
        name: "Currywurst und Pommes",
        text: "Leckere Schweinsbratwurst mit hausgemachter Currysauce dazu Pommens",
        filter: ['hauptgang', 'halal', 'kleiner hunger', 'kids menü', 'kinder'],
        price: 9.99,
    },
    {
        id: '52',
        name: "Schnitzel Wiener Art mit Pommes",
        text: "Leckere Schweineschnitzel mit Salatbukett und dazu Pommens",
        filter: ['hauptgang', 'halal', 'kleiner hunger', 'kids menü', 'kinder'],
        price: 10.99,
    },
    {
        id: '53',
        name: "Gebratene Ente mit Reis",
        text: "Knusprige gebackene Entenbrust auf Reis",
        filter: ['hauptgang', 'halal'],
        price: 9.99,
    },
    {
        id: '54',
        name: "Spaghetti Bolonaise",
        text: "Herzhafte Rinderbolonaise nach Italienischem Originalrezept auf Spaghetti",
        filter: ['hauptgang', 'halal', 'kids menü', 'kinder'],
        price: 7.49,
    },
    {
        id: '55',
        name: "Pommes",
        text: "Knusprige gebackene Pommes Frites",
        filter: ['hauptgang', 'halal', 'kids menü', 'kinder', 'kleiner hunger', 'vorspeise', 'vegan', 'vegetarisch',
        ],
        price: 2.99,
    },
    {
        id: '80',
        name: 'Orangen Mohnpafait',
        text: 'Halbgefrohrenes hausgemachtes Parfait, mit Orangenfilet und Mohn',
        filter: ['dessert', 'halal', 'vegetarisch', 'kids menü', 'kinder', 'kleiner hunger'],
        price: 8.99,
    },
    {
        id: '81',
        name: 'Vanille Eis',
        text: '1 Kugel Vanilleeis',
        filter: ['dessert', 'halal', 'vegetarisch', 'kids menü', 'kinder', 'kleiner hunger'],
        price: 1.99,
    },
    {
        id: '82',
        name: 'Schoko Eis',
        text: '1 Kugel Schokoladeneis',
        filter: ['dessert', 'halal', 'vegetarisch', 'kids menü', 'kinder', 'kleiner hunger'],
        price: 1.99,
    },
    {
        id: '82',
        name: 'Erdbeer Eis',
        text: '1 Kugel Erdbeereis',
        filter: ['dessert', 'halal', 'vegetarisch', 'kids menü', 'kinder', 'kleiner hunger'],
        price: 1.99,
    }

];



